name: Prepare Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Run Changesets
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    outputs:
      published: ${{ steps.changesets.outputs.published }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm ci

      - name: Create Release PR or Publish
        id: changesets
        uses: changesets/action@v1
        with:
          publish: npm run release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  update-docs:
    name: Update Docs
    runs-on: ubuntu-latest
    needs: release
    if: needs.release.outputs.published == 'true'
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci
        working-directory: ./docs

      - name: Install latest groundwork-water
        run: npm install "usace-watermanagement/groundwork-water@latest"
        working-directory: ./docs

      - name: Build docs
        env:
          VITE_HOMEPAGE: "https://usace-watermanagement.github.io/groundwork-water"
        run: npx vite build
        working-directory: ./docs

      - name: Upload production-ready docs
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./docs/dist

  deploy-docs:
    name: Deploy Docs to GH Pages
    runs-on: ubuntu-latest
    needs: update-docs
    if: needs.release.outputs.published == 'true'
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
